### PR TITLE
Merge pull request #1 from projectara/master

### PR DESCRIPTION
**Pull request by ChrisMyerchin**
gab latest

### CODE REVIEW

**Comment by ChrisMyerchin** [comment]
update fork

**Comment by ghost** [comment]
Hi Chris,

I've never seen any pull request emails from github.

The LeafLabs process is (once you get approval on RB)
rebase from github master
squash local changes on top of master
push to master

So there is no pull/request.
What's this about?

Thanks,
Darryl

**Comment by ChrisMyerchin** [comment]
darn it.

I was just using GitHub GUI interface to re-sync my fork master (
https://github.com/ChrisMyerchin/nuttx/tree/master) to the
projectara/master.

Looks like I've still got some learning to do...

-Chris

**Comment by gregkh** [comment]
Just push properly, no pull request needed for firmware.

**Pull request closed without merging**
